title: "Self++"
description: "You plus a bit more"
baseurl: "/SelfPlusPlus"   # IMPORTANT for project sites
url: "https://s-k-y-h-i-g-h.github.io"
remote_theme: "mmistakes/minimal-mistakes"
markdown: GFM              # GitHub Flavored Markdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "site"